services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: db-manager-products
    volumes:
      - ./data:/var/lib/postgresql/data 
  
  app:
    env_file:
      - .env.docker
    depends_on:
      - db
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
